// Migration 0001 (B-M24-02): the initial schema. FROZEN: this text is recorded with its SHA-256 in schema_migrations
// when applied, and a changed text refuses entries at start (E_MIGRATION_CHECKSUM). Generated once from the table
// descriptors (schema.ts, ddl.ts); later schema changes are new numbered migrations, never edits here.
// 118 statements: 52 tables (every table of schema.ts except schema_migrations, which the
// migration runner creates), their indexes, the append-only triggers and the signal update-once trigger.
// Regenerated in Z02 rounds 2 and 3, before it was applied anywhere: login tables moved out (ruling 1), metric_rollup_1m
// scope (ruling 7); the delete triggers need a row old by both retention_clock and SQLite's wall clock (rulings 10, 14).
import type { Migration } from '../migrate.ts';

export const M0001_INITIAL: Migration = {
  version: 1,
  name: 'initial',
  statements: [
  `CREATE TABLE "run" (
  "run_id" TEXT NOT NULL CHECK (length("run_id") = 26 AND "run_id" NOT GLOB '*[^0-9A-HJKMNP-TV-Z]*'),
  "mode" TEXT NOT NULL CHECK ("mode" IN ('backtest', 'replay', 'coarse_screen', 'paper', 'live_small', 'live')),
  "strategy_id" TEXT NOT NULL,
  "trial_key" TEXT NOT NULL,
  "dataset_hashes" TEXT NOT NULL CHECK (json_valid("dataset_hashes")),
  "git_commit" TEXT NOT NULL,
  "seed" INTEGER NOT NULL,
  "status" TEXT NOT NULL,
  "started_at" INTEGER NOT NULL CHECK ("started_at" >= 1000000000000 AND "started_at" < 100000000000000),
  "ended_at" INTEGER CHECK ("ended_at" IS NULL OR ("ended_at" >= 1000000000000 AND "ended_at" < 100000000000000)),
  "bundle_sha256" TEXT CHECK ("bundle_sha256" IS NULL OR (length("bundle_sha256") = 64 AND "bundle_sha256" NOT GLOB '*[^0-9a-f]*')),
  "bundle_signature_ok" INTEGER CHECK ("bundle_signature_ok" IS NULL OR ("bundle_signature_ok" IN (0, 1))),
  "imported_at" INTEGER CHECK ("imported_at" IS NULL OR ("imported_at" >= 1000000000000 AND "imported_at" < 100000000000000)),
  "data_from" INTEGER CHECK ("data_from" IS NULL OR ("data_from" >= 1000000000000 AND "data_from" < 100000000000000)),
  "data_to" INTEGER CHECK ("data_to" IS NULL OR ("data_to" >= 1000000000000 AND "data_to" < 100000000000000)),
  "trades_count" INTEGER,
  "low_coverage" INTEGER CHECK ("low_coverage" IS NULL OR ("low_coverage" IN (0, 1))),
  "gate_ids_evaluated" TEXT CHECK ("gate_ids_evaluated" IS NULL OR (json_valid("gate_ids_evaluated"))),
  "created_at" INTEGER NOT NULL CHECK ("created_at" >= 1000000000000 AND "created_at" < 100000000000000),
  PRIMARY KEY ("run_id")
) STRICT`,
  `CREATE TABLE "system_state" (
  "id" INTEGER NOT NULL,
  "mode" TEXT NOT NULL CHECK ("mode" IN ('backtest', 'replay', 'paper', 'live_small', 'live')),
  "trading_state" TEXT NOT NULL CHECK ("trading_state" IN ('starting', 'running', 'halt_requested', 'halted', 'halt_partial', 'resume_requested', 'exits_only', 'stopped')),
  "state_version" INTEGER NOT NULL,
  "mode_since" INTEGER NOT NULL CHECK ("mode_since" >= 1000000000000 AND "mode_since" < 100000000000000),
  "cooldown_until" INTEGER CHECK ("cooldown_until" IS NULL OR ("cooldown_until" >= 1000000000000 AND "cooldown_until" < 100000000000000)),
  "created_at" INTEGER NOT NULL CHECK ("created_at" >= 1000000000000 AND "created_at" < 100000000000000),
  "updated_at" INTEGER NOT NULL CHECK ("updated_at" >= 1000000000000 AND "updated_at" < 100000000000000),
  PRIMARY KEY ("id")
) STRICT`,
  `CREATE TABLE "config_version" (
  "config_version" TEXT NOT NULL CHECK (length("config_version") = 64 AND "config_version" NOT GLOB '*[^0-9a-f]*'),
  "version_no" INTEGER NOT NULL,
  "json" TEXT NOT NULL CHECK (json_valid("json")),
  "applied_at" INTEGER NOT NULL CHECK ("applied_at" >= 1000000000000 AND "applied_at" < 100000000000000),
  "applied_by" TEXT NOT NULL CHECK (json_valid("applied_by")),
  "created_at" INTEGER NOT NULL CHECK ("created_at" >= 1000000000000 AND "created_at" < 100000000000000),
  PRIMARY KEY ("config_version"),
  UNIQUE ("version_no")
) STRICT`,
  `CREATE TRIGGER "config_version_no_update" BEFORE UPDATE ON "config_version" BEGIN SELECT RAISE(ABORT, 'append_only'); END`,
  `CREATE TRIGGER "config_version_no_delete" BEFORE DELETE ON "config_version" BEGIN SELECT RAISE(ABORT, 'append_only'); END`,
  `CREATE TABLE "strategy" (
  "strategy_id" TEXT NOT NULL,
  "version" INTEGER NOT NULL,
  "params_hash" TEXT NOT NULL CHECK (length("params_hash") = 64 AND "params_hash" NOT GLOB '*[^0-9a-f]*'),
  "enabled_modes" TEXT NOT NULL CHECK (json_valid("enabled_modes")),
  "created_at" INTEGER NOT NULL CHECK ("created_at" >= 1000000000000 AND "created_at" < 100000000000000),
  "updated_at" INTEGER NOT NULL CHECK ("updated_at" >= 1000000000000 AND "updated_at" < 100000000000000),
  PRIMARY KEY ("strategy_id", "version")
) STRICT`,
  `CREATE TABLE "token" (
  "mint" TEXT NOT NULL CHECK (length("mint") BETWEEN 32 AND 44 AND "mint" NOT GLOB '*[^1-9A-HJ-NP-Za-km-z]*'),
  "token_program" TEXT NOT NULL CHECK ("token_program" IN ('spl_token', 'token_2022', 'unknown')),
  "decimals" INTEGER NOT NULL,
  "symbol" TEXT CHECK ("symbol" IS NULL OR (length(CAST("symbol" AS BLOB)) <= 32)),
  "name" TEXT CHECK ("name" IS NULL OR (length(CAST("name" AS BLOB)) <= 64)),
  "metadata_update_authority" TEXT CHECK ("metadata_update_authority" IS NULL OR (length("metadata_update_authority") BETWEEN 32 AND 44 AND "metadata_update_authority" NOT GLOB '*[^1-9A-HJ-NP-Za-km-z]*')),
  "first_seen_at" INTEGER NOT NULL CHECK ("first_seen_at" >= 1000000000000 AND "first_seen_at" < 100000000000000),
  "symbol_collision_count" INTEGER NOT NULL,
  "refreshed_at" INTEGER NOT NULL CHECK ("refreshed_at" >= 1000000000000 AND "refreshed_at" < 100000000000000),
  "created_at" INTEGER NOT NULL CHECK ("created_at" >= 1000000000000 AND "created_at" < 100000000000000),
  PRIMARY KEY ("mint")
) STRICT`,
  `CREATE TABLE "mint_class" (
  "mint" TEXT NOT NULL CHECK (length("mint") BETWEEN 32 AND 44 AND "mint" NOT GLOB '*[^1-9A-HJ-NP-Za-km-z]*'),
  "class" TEXT NOT NULL CHECK ("class" IN ('ours', 'unsolicited', 'written_off')),
  "since" INTEGER NOT NULL CHECK ("since" >= 1000000000000 AND "since" < 100000000000000),
  "set_by" TEXT NOT NULL,
  "created_at" INTEGER NOT NULL CHECK ("created_at" >= 1000000000000 AND "created_at" < 100000000000000),
  PRIMARY KEY ("mint")
) STRICT`,
  `CREATE TABLE "pool" (
  "pool_id" TEXT NOT NULL CHECK (length("pool_id") BETWEEN 32 AND 44 AND "pool_id" NOT GLOB '*[^1-9A-HJ-NP-Za-km-z]*'),
  "venue" TEXT NOT NULL CHECK ("venue" IN ('pump_curve', 'pumpswap', 'raydium_amm_v4', 'raydium_cpmm')),
  "base_mint" TEXT NOT NULL CHECK (length("base_mint") BETWEEN 32 AND 44 AND "base_mint" NOT GLOB '*[^1-9A-HJ-NP-Za-km-z]*'),
  "quote_mint" TEXT NOT NULL CHECK (length("quote_mint") BETWEEN 32 AND 44 AND "quote_mint" NOT GLOB '*[^1-9A-HJ-NP-Za-km-z]*'),
  "is_canonical" INTEGER NOT NULL CHECK ("is_canonical" IN (0, 1)),
  "created_slot" INTEGER,
  "quarantined_at" INTEGER CHECK ("quarantined_at" IS NULL OR ("quarantined_at" >= 1000000000000 AND "quarantined_at" < 100000000000000)),
  "quarantine_reason" TEXT,
  "created_at" INTEGER NOT NULL CHECK ("created_at" >= 1000000000000 AND "created_at" < 100000000000000),
  "updated_at" INTEGER NOT NULL CHECK ("updated_at" >= 1000000000000 AND "updated_at" < 100000000000000),
  PRIMARY KEY ("pool_id")
) STRICT`,
  `CREATE TABLE "screen_result" (
  "screen_id" TEXT NOT NULL CHECK (length("screen_id") = 26 AND "screen_id" NOT GLOB '*[^0-9A-HJKMNP-TV-Z]*'),
  "mint" TEXT NOT NULL CHECK (length("mint") BETWEEN 32 AND 44 AND "mint" NOT GLOB '*[^1-9A-HJ-NP-Za-km-z]*'),
  "pool_id" TEXT NOT NULL CHECK (length("pool_id") BETWEEN 32 AND 44 AND "pool_id" NOT GLOB '*[^1-9A-HJ-NP-Za-km-z]*'),
  "as_of_slot" INTEGER NOT NULL,
  "verdict" TEXT NOT NULL,
  "checks_json" TEXT NOT NULL CHECK (json_valid("checks_json")),
  "purpose" TEXT NOT NULL,
  "created_at" INTEGER NOT NULL CHECK ("created_at" >= 1000000000000 AND "created_at" < 100000000000000),
  PRIMARY KEY ("screen_id")
) STRICT`,
  `CREATE INDEX "screen_result_mint_pool_slot" ON "screen_result" ("mint", "pool_id", "as_of_slot")`,
  `CREATE TRIGGER "screen_result_no_update" BEFORE UPDATE ON "screen_result" BEGIN SELECT RAISE(ABORT, 'append_only'); END`,
  `CREATE TRIGGER "screen_result_no_delete" BEFORE DELETE ON "screen_result" WHEN OLD."created_at" > coalesce((SELECT "now_ms" FROM "retention_clock" WHERE "id" = 1), 0) - 31622400 * 1000 OR OLD."created_at" > (unixepoch('now') - 31622400) * 1000 BEGIN SELECT RAISE(ABORT, 'append_only'); END`,
  `CREATE TABLE "candidate" (
  "candidate_id" TEXT NOT NULL CHECK (length("candidate_id") = 26 AND "candidate_id" NOT GLOB '*[^0-9A-HJKMNP-TV-Z]*'),
  "mint" TEXT NOT NULL CHECK (length("mint") BETWEEN 32 AND 44 AND "mint" NOT GLOB '*[^1-9A-HJ-NP-Za-km-z]*'),
  "pool_id" TEXT NOT NULL CHECK (length("pool_id") BETWEEN 32 AND 44 AND "pool_id" NOT GLOB '*[^1-9A-HJ-NP-Za-km-z]*'),
  "venue" TEXT NOT NULL CHECK ("venue" IN ('pump_curve', 'pumpswap', 'raydium_amm_v4', 'raydium_cpmm')),
  "state" TEXT NOT NULL CHECK ("state" IN ('discovered', 'prefiltered_out', 'screening', 'rejected', 'eligible', 'watched', 'signalled', 'in_position', 'cooldown', 'blacklisted', 'stale', 'evicted')),
  "reasons" TEXT NOT NULL CHECK (json_valid("reasons")),
  "cooldown_until" INTEGER CHECK ("cooldown_until" IS NULL OR ("cooldown_until" >= 1000000000000 AND "cooldown_until" < 100000000000000)),
  "first_seen_at" INTEGER NOT NULL CHECK ("first_seen_at" >= 1000000000000 AND "first_seen_at" < 100000000000000),
  "last_screen_id" TEXT CHECK ("last_screen_id" IS NULL OR (length("last_screen_id") = 26 AND "last_screen_id" NOT GLOB '*[^0-9A-HJKMNP-TV-Z]*')),
  "version" INTEGER NOT NULL,
  "created_at" INTEGER NOT NULL CHECK ("created_at" >= 1000000000000 AND "created_at" < 100000000000000),
  "updated_at" INTEGER NOT NULL CHECK ("updated_at" >= 1000000000000 AND "updated_at" < 100000000000000),
  PRIMARY KEY ("candidate_id"),
  UNIQUE ("mint", "pool_id")
) STRICT`,
  `CREATE INDEX "candidate_state" ON "candidate" ("state")`,
  `CREATE TABLE "signal" (
  "candidate_id" TEXT NOT NULL CHECK (length("candidate_id") = 26 AND "candidate_id" NOT GLOB '*[^0-9A-HJKMNP-TV-Z]*'),
  "strategy_id" TEXT NOT NULL,
  "score" TEXT CHECK ("score" IS NULL OR (length("score") <= 100 AND (CASE WHEN "score" GLOB '-*' THEN substr("score", 2) ELSE "score" END) GLOB '[0-9]*' AND (CASE WHEN "score" GLOB '-*' THEN substr("score", 2) ELSE "score" END) NOT GLOB '*[^0-9.]*' AND (CASE WHEN "score" GLOB '-*' THEN substr("score", 2) ELSE "score" END) NOT GLOB '*.*.*' AND (CASE WHEN "score" GLOB '-*' THEN substr("score", 2) ELSE "score" END) NOT GLOB '*.' AND (CASE WHEN "score" GLOB '-*' THEN substr("score", 2) ELSE "score" END) NOT GLOB '0[0-9]*' AND (instr((CASE WHEN "score" GLOB '-*' THEN substr("score", 2) ELSE "score" END), '.') = 0 OR length((CASE WHEN "score" GLOB '-*' THEN substr("score", 2) ELSE "score" END)) - instr((CASE WHEN "score" GLOB '-*' THEN substr("score", 2) ELSE "score" END), '.') <= 30))),
  "score_unit" TEXT NOT NULL,
  "decision" TEXT NOT NULL CHECK ("decision" IN ('pending', 'accepted', 'rejected', 'expired', 'error')),
  "decided_at" INTEGER CHECK ("decided_at" IS NULL OR ("decided_at" >= 1000000000000 AND "decided_at" < 100000000000000)),
  "decision_latency_ms" REAL,
  "risk_checks_json" TEXT CHECK ("risk_checks_json" IS NULL OR (json_valid("risk_checks_json"))),
  "intended_size_lamports" INTEGER CHECK ("intended_size_lamports" IS NULL OR ("intended_size_lamports" >= 0)),
  "expected_cost_bps" INTEGER,
  "quote_age_ms" REAL,
  "created_at" INTEGER NOT NULL CHECK ("created_at" >= 1000000000000 AND "created_at" < 100000000000000),
  PRIMARY KEY ("candidate_id")
) STRICT`,
  `CREATE TRIGGER "signal_update_once" BEFORE UPDATE ON "signal" WHEN OLD."decided_at" IS NOT NULL OR NEW."candidate_id" IS NOT OLD."candidate_id" OR NEW."strategy_id" IS NOT OLD."strategy_id" OR NEW."score" IS NOT OLD."score" OR NEW."score_unit" IS NOT OLD."score_unit" OR NEW."created_at" IS NOT OLD."created_at" BEGIN SELECT RAISE(ABORT, 'append_only'); END`,
  `CREATE TABLE "order_intent" (
  "intent_id" TEXT NOT NULL CHECK (length("intent_id") = 26 AND "intent_id" NOT GLOB '*[^0-9A-HJKMNP-TV-Z]*'),
  "idempotency_key" TEXT NOT NULL,
  "position_id" TEXT CHECK ("position_id" IS NULL OR (length("position_id") = 26 AND "position_id" NOT GLOB '*[^0-9A-HJKMNP-TV-Z]*')),
  "side" TEXT NOT NULL CHECK ("side" IN ('buy', 'sell')),
  "mint" TEXT NOT NULL CHECK (length("mint") BETWEEN 32 AND 44 AND "mint" NOT GLOB '*[^1-9A-HJ-NP-Za-km-z]*'),
  "pool_id" TEXT NOT NULL CHECK (length("pool_id") BETWEEN 32 AND 44 AND "pool_id" NOT GLOB '*[^1-9A-HJ-NP-Za-km-z]*'),
  "amount_in" TEXT NOT NULL CHECK ("amount_in" <> '' AND "amount_in" NOT GLOB '*[^0-9]*' AND ("amount_in" = '0' OR "amount_in" NOT GLOB '0*') AND (length("amount_in") < 20 OR (length("amount_in") = 20 AND "amount_in" <= '18446744073709551615'))),
  "min_out_bps" INTEGER NOT NULL,
  "max_slippage_bps" INTEGER NOT NULL,
  "reason" TEXT NOT NULL,
  "urgency" TEXT NOT NULL,
  "state" TEXT NOT NULL CHECK ("state" IN ('created', 'risk_checking', 'rejected', 'reserved', 'building', 'signing', 'in_flight', 'filled', 'failed', 'expired_final', 'cancelled', 'reconciling', 'abandoned')),
  "version" INTEGER NOT NULL,
  "mode" TEXT NOT NULL CHECK ("mode" IN ('backtest', 'replay', 'paper', 'live_small', 'live')),
  "purpose" TEXT NOT NULL DEFAULT 'trade' CHECK ("purpose" IN ('trade', 'janitor', 'sweep', 'close_unsolicited')),
  "created_at" INTEGER NOT NULL CHECK ("created_at" >= 1000000000000 AND "created_at" < 100000000000000),
  "updated_at" INTEGER NOT NULL CHECK ("updated_at" >= 1000000000000 AND "updated_at" < 100000000000000),
  PRIMARY KEY ("intent_id"),
  UNIQUE ("idempotency_key")
) STRICT`,
  `CREATE UNIQUE INDEX "order_intent_pertoken" ON "order_intent" ("mint") WHERE side = 'buy' AND state NOT IN ('rejected','filled','expired_final','cancelled','abandoned','failed')`,
  `CREATE INDEX "order_intent_position" ON "order_intent" ("position_id")`,
  `CREATE TABLE "tx_attempt" (
  "attempt_id" TEXT NOT NULL CHECK (length("attempt_id") = 26 AND "attempt_id" NOT GLOB '*[^0-9A-HJKMNP-TV-Z]*'),
  "intent_id" TEXT NOT NULL CHECK (length("intent_id") = 26 AND "intent_id" NOT GLOB '*[^0-9A-HJKMNP-TV-Z]*'),
  "attempt_no" INTEGER NOT NULL,
  "rung" INTEGER NOT NULL,
  "path" TEXT NOT NULL,
  "cu_limit" INTEGER NOT NULL,
  "cu_price" INTEGER NOT NULL,
  "tips_json" TEXT NOT NULL CHECK (json_valid("tips_json")),
  "sell_amount_base" TEXT CHECK ("sell_amount_base" IS NULL OR ("sell_amount_base" <> '' AND "sell_amount_base" NOT GLOB '*[^0-9]*' AND ("sell_amount_base" = '0' OR "sell_amount_base" NOT GLOB '0*') AND (length("sell_amount_base") < 20 OR (length("sell_amount_base") = 20 AND "sell_amount_base" <= '18446744073709551615')))),
  "balance_read_slot" INTEGER,
  "last_valid_block_height" INTEGER,
  "status" TEXT NOT NULL CHECK ("status" IN ('building', 'build_failed', 'signing', 'sign_refused', 'sending', 'sent', 'landed_processed', 'confirmed_success', 'confirmed_failed', 'expired', 'unknown')),
  "failure_class" TEXT CHECK ("failure_class" IS NULL OR ("failure_class" IN ('slippage', 'compute_exceeded', 'insufficient_funds_fee', 'account_state', 'balance_mismatch', 'venue_disabled', 'token_program_refusal', 'blockhash_expired', 'unknown'))),
  "signature" TEXT CHECK ("signature" IS NULL OR (length("signature") BETWEEN 64 AND 88 AND "signature" NOT GLOB '*[^1-9A-HJ-NP-Za-km-z]*')),
  "slot" INTEGER,
  "err" TEXT,
  "fee_lamports" INTEGER CHECK ("fee_lamports" IS NULL OR ("fee_lamports" >= 0)),
  "expiry_proof_json" TEXT CHECK ("expiry_proof_json" IS NULL OR (json_valid("expiry_proof_json"))),
  "first_sent_at" INTEGER CHECK ("first_sent_at" IS NULL OR ("first_sent_at" >= 1000000000000 AND "first_sent_at" < 100000000000000)),
  "confirmed_at" INTEGER CHECK ("confirmed_at" IS NULL OR ("confirmed_at" >= 1000000000000 AND "confirmed_at" < 100000000000000)),
  "signed_tx_b64" TEXT,
  "classification_json" TEXT CHECK ("classification_json" IS NULL OR (json_valid("classification_json"))),
  "lvbh_source" TEXT CHECK ("lvbh_source" IS NULL OR ("lvbh_source" IN ('blockhash', 'derived_upper_bound'))),
  "route" TEXT,
  "jupiter_fee_bps" INTEGER,
  "version" INTEGER NOT NULL,
  "created_at" INTEGER NOT NULL CHECK ("created_at" >= 1000000000000 AND "created_at" < 100000000000000),
  "updated_at" INTEGER NOT NULL CHECK ("updated_at" >= 1000000000000 AND "updated_at" < 100000000000000),
  PRIMARY KEY ("attempt_id"),
  UNIQUE ("signature")
) STRICT`,
  `CREATE INDEX "tx_attempt_intent" ON "tx_attempt" ("intent_id")`,
  `CREATE TABLE "fill" (
  "fill_id" TEXT NOT NULL CHECK (length("fill_id") = 26 AND "fill_id" NOT GLOB '*[^0-9A-HJKMNP-TV-Z]*'),
  "attempt_id" TEXT CHECK ("attempt_id" IS NULL OR (length("attempt_id") = 26 AND "attempt_id" NOT GLOB '*[^0-9A-HJKMNP-TV-Z]*')),
  "intent_id" TEXT CHECK ("intent_id" IS NULL OR (length("intent_id") = 26 AND "intent_id" NOT GLOB '*[^0-9A-HJKMNP-TV-Z]*')),
  "position_id" TEXT NOT NULL CHECK (length("position_id") = 26 AND "position_id" NOT GLOB '*[^0-9A-HJKMNP-TV-Z]*'),
  "side" TEXT NOT NULL CHECK ("side" IN ('buy', 'sell')),
  "signature" TEXT CHECK ("signature" IS NULL OR (length("signature") BETWEEN 64 AND 88 AND "signature" NOT GLOB '*[^1-9A-HJ-NP-Za-km-z]*')),
  "sol_delta_lamports" INTEGER NOT NULL,
  "token_delta_base" TEXT NOT NULL CHECK ((CASE WHEN "token_delta_base" GLOB '-*' THEN substr("token_delta_base", 2) ELSE "token_delta_base" END) <> '' AND (CASE WHEN "token_delta_base" GLOB '-*' THEN substr("token_delta_base", 2) ELSE "token_delta_base" END) NOT GLOB '*[^0-9]*' AND ((CASE WHEN "token_delta_base" GLOB '-*' THEN substr("token_delta_base", 2) ELSE "token_delta_base" END) = '0' OR (CASE WHEN "token_delta_base" GLOB '-*' THEN substr("token_delta_base", 2) ELSE "token_delta_base" END) NOT GLOB '0*') AND length((CASE WHEN "token_delta_base" GLOB '-*' THEN substr("token_delta_base", 2) ELSE "token_delta_base" END)) <= 39 AND "token_delta_base" <> '-0'),
  "venue_fee_lamports" INTEGER NOT NULL CHECK ("venue_fee_lamports" >= 0),
  "network_fee_lamports" INTEGER NOT NULL CHECK ("network_fee_lamports" >= 0),
  "tip_lamports" INTEGER NOT NULL CHECK ("tip_lamports" >= 0),
  "simulated" INTEGER NOT NULL CHECK ("simulated" IN (0, 1)),
  "source" TEXT NOT NULL CHECK ("source" IN ('live', 'paper', 'sentinel', 'recovered')),
  "slot" INTEGER,
  "block_time" INTEGER CHECK ("block_time" IS NULL OR ("block_time" >= 1000000000000 AND "block_time" < 100000000000000)),
  "at" INTEGER NOT NULL CHECK ("at" >= 1000000000000 AND "at" < 100000000000000),
  "created_at" INTEGER NOT NULL CHECK ("created_at" >= 1000000000000 AND "created_at" < 100000000000000),
  PRIMARY KEY ("fill_id")
) STRICT`,
  `CREATE INDEX "fill_position" ON "fill" ("position_id")`,
  `CREATE TRIGGER "fill_no_update" BEFORE UPDATE ON "fill" BEGIN SELECT RAISE(ABORT, 'append_only'); END`,
  `CREATE TRIGGER "fill_no_delete" BEFORE DELETE ON "fill" WHEN OLD."created_at" > coalesce((SELECT "now_ms" FROM "retention_clock" WHERE "id" = 1), 0) - 220924800 * 1000 OR OLD."created_at" > (unixepoch('now') - 220924800) * 1000 BEGIN SELECT RAISE(ABORT, 'append_only'); END`,
  `CREATE TABLE "position" (
  "position_id" TEXT NOT NULL CHECK (length("position_id") = 26 AND "position_id" NOT GLOB '*[^0-9A-HJKMNP-TV-Z]*'),
  "mode" TEXT NOT NULL CHECK ("mode" IN ('backtest', 'replay', 'paper', 'live_small', 'live')),
  "strategy_id" TEXT NOT NULL,
  "mint" TEXT NOT NULL CHECK (length("mint") BETWEEN 32 AND 44 AND "mint" NOT GLOB '*[^1-9A-HJ-NP-Za-km-z]*'),
  "pool_id" TEXT NOT NULL CHECK (length("pool_id") BETWEEN 32 AND 44 AND "pool_id" NOT GLOB '*[^1-9A-HJ-NP-Za-km-z]*'),
  "state" TEXT NOT NULL CHECK ("state" IN ('opening', 'open', 'partially_closed', 'closing', 'close_failed', 'stuck', 'closed', 'open_failed', 'orphan', 'written_off')),
  "size_base" TEXT NOT NULL CHECK ("size_base" <> '' AND "size_base" NOT GLOB '*[^0-9]*' AND ("size_base" = '0' OR "size_base" NOT GLOB '0*') AND (length("size_base") < 20 OR (length("size_base") = 20 AND "size_base" <= '18446744073709551615'))),
  "entry_cost_lamports" INTEGER NOT NULL CHECK ("entry_cost_lamports" >= 0),
  "entry_price_sol_per_token" TEXT CHECK ("entry_price_sol_per_token" IS NULL OR (length("entry_price_sol_per_token") <= 100 AND (CASE WHEN "entry_price_sol_per_token" GLOB '-*' THEN substr("entry_price_sol_per_token", 2) ELSE "entry_price_sol_per_token" END) GLOB '[0-9]*' AND (CASE WHEN "entry_price_sol_per_token" GLOB '-*' THEN substr("entry_price_sol_per_token", 2) ELSE "entry_price_sol_per_token" END) NOT GLOB '*[^0-9.]*' AND (CASE WHEN "entry_price_sol_per_token" GLOB '-*' THEN substr("entry_price_sol_per_token", 2) ELSE "entry_price_sol_per_token" END) NOT GLOB '*.*.*' AND (CASE WHEN "entry_price_sol_per_token" GLOB '-*' THEN substr("entry_price_sol_per_token", 2) ELSE "entry_price_sol_per_token" END) NOT GLOB '*.' AND (CASE WHEN "entry_price_sol_per_token" GLOB '-*' THEN substr("entry_price_sol_per_token", 2) ELSE "entry_price_sol_per_token" END) NOT GLOB '0[0-9]*' AND (instr((CASE WHEN "entry_price_sol_per_token" GLOB '-*' THEN substr("entry_price_sol_per_token", 2) ELSE "entry_price_sol_per_token" END), '.') = 0 OR length((CASE WHEN "entry_price_sol_per_token" GLOB '-*' THEN substr("entry_price_sol_per_token", 2) ELSE "entry_price_sol_per_token" END)) - instr((CASE WHEN "entry_price_sol_per_token" GLOB '-*' THEN substr("entry_price_sol_per_token", 2) ELSE "entry_price_sol_per_token" END), '.') <= 30))),
  "exit_plan_json" TEXT NOT NULL CHECK (json_valid("exit_plan_json")),
  "triggers_json" TEXT NOT NULL CHECK (json_valid("triggers_json")),
  "high_water" TEXT CHECK ("high_water" IS NULL OR (length("high_water") <= 100 AND (CASE WHEN "high_water" GLOB '-*' THEN substr("high_water", 2) ELSE "high_water" END) GLOB '[0-9]*' AND (CASE WHEN "high_water" GLOB '-*' THEN substr("high_water", 2) ELSE "high_water" END) NOT GLOB '*[^0-9.]*' AND (CASE WHEN "high_water" GLOB '-*' THEN substr("high_water", 2) ELSE "high_water" END) NOT GLOB '*.*.*' AND (CASE WHEN "high_water" GLOB '-*' THEN substr("high_water", 2) ELSE "high_water" END) NOT GLOB '*.' AND (CASE WHEN "high_water" GLOB '-*' THEN substr("high_water", 2) ELSE "high_water" END) NOT GLOB '0[0-9]*' AND (instr((CASE WHEN "high_water" GLOB '-*' THEN substr("high_water", 2) ELSE "high_water" END), '.') = 0 OR length((CASE WHEN "high_water" GLOB '-*' THEN substr("high_water", 2) ELSE "high_water" END)) - instr((CASE WHEN "high_water" GLOB '-*' THEN substr("high_water", 2) ELSE "high_water" END), '.') <= 30))),
  "close_failed_reason" TEXT,
  "source" TEXT NOT NULL,
  "opened_at" INTEGER CHECK ("opened_at" IS NULL OR ("opened_at" >= 1000000000000 AND "opened_at" < 100000000000000)),
  "closed_at" INTEGER CHECK ("closed_at" IS NULL OR ("closed_at" >= 1000000000000 AND "closed_at" < 100000000000000)),
  "version" INTEGER NOT NULL,
  "created_at" INTEGER NOT NULL CHECK ("created_at" >= 1000000000000 AND "created_at" < 100000000000000),
  "updated_at" INTEGER NOT NULL CHECK ("updated_at" >= 1000000000000 AND "updated_at" < 100000000000000),
  PRIMARY KEY ("position_id")
) STRICT`,
  `CREATE UNIQUE INDEX "position_pertoken" ON "position" ("mint") WHERE state NOT IN ('closed','open_failed','written_off')`,
  `CREATE TABLE "position_event" (
  "event_id" TEXT NOT NULL CHECK (length("event_id") = 26 AND "event_id" NOT GLOB '*[^0-9A-HJKMNP-TV-Z]*'),
  "position_id" TEXT NOT NULL CHECK (length("position_id") = 26 AND "position_id" NOT GLOB '*[^0-9A-HJKMNP-TV-Z]*'),
  "from_state" TEXT CHECK ("from_state" IS NULL OR ("from_state" IN ('opening', 'open', 'partially_closed', 'closing', 'close_failed', 'stuck', 'closed', 'open_failed', 'orphan', 'written_off'))),
  "to_state" TEXT NOT NULL CHECK ("to_state" IN ('opening', 'open', 'partially_closed', 'closing', 'close_failed', 'stuck', 'closed', 'open_failed', 'orphan', 'written_off')),
  "cause" TEXT NOT NULL,
  "at" INTEGER NOT NULL CHECK ("at" >= 1000000000000 AND "at" < 100000000000000),
  "created_at" INTEGER NOT NULL CHECK ("created_at" >= 1000000000000 AND "created_at" < 100000000000000),
  PRIMARY KEY ("event_id")
) STRICT`,
  `CREATE INDEX "position_event_position" ON "position_event" ("position_id")`,
  `CREATE TRIGGER "position_event_no_update" BEFORE UPDATE ON "position_event" BEGIN SELECT RAISE(ABORT, 'append_only'); END`,
  `CREATE TRIGGER "position_event_no_delete" BEFORE DELETE ON "position_event" WHEN OLD."created_at" > coalesce((SELECT "now_ms" FROM "retention_clock" WHERE "id" = 1), 0) - 220924800 * 1000 OR OLD."created_at" > (unixepoch('now') - 220924800) * 1000 BEGIN SELECT RAISE(ABORT, 'append_only'); END`,
  `CREATE TABLE "trade" (
  "trade_id" TEXT NOT NULL CHECK (length("trade_id") = 26 AND "trade_id" NOT GLOB '*[^0-9A-HJKMNP-TV-Z]*'),
  "position_id" TEXT NOT NULL CHECK (length("position_id") = 26 AND "position_id" NOT GLOB '*[^0-9A-HJKMNP-TV-Z]*'),
  "run_id" TEXT CHECK ("run_id" IS NULL OR (length("run_id") = 26 AND "run_id" NOT GLOB '*[^0-9A-HJKMNP-TV-Z]*')),
  "mode" TEXT NOT NULL CHECK ("mode" IN ('backtest', 'replay', 'paper', 'live_small', 'live')),
  "simulated" INTEGER NOT NULL CHECK ("simulated" IN (0, 1)),
  "strategy_id" TEXT NOT NULL,
  "mint" TEXT NOT NULL CHECK (length("mint") BETWEEN 32 AND 44 AND "mint" NOT GLOB '*[^1-9A-HJ-NP-Za-km-z]*'),
  "symbol" TEXT CHECK ("symbol" IS NULL OR (length(CAST("symbol" AS BLOB)) <= 32)),
  "decimals" INTEGER,
  "opened_at" INTEGER NOT NULL CHECK ("opened_at" >= 1000000000000 AND "opened_at" < 100000000000000),
  "closed_at" INTEGER NOT NULL CHECK ("closed_at" >= 1000000000000 AND "closed_at" < 100000000000000),
  "hold_ms" REAL NOT NULL,
  "size_base" TEXT NOT NULL CHECK ("size_base" <> '' AND "size_base" NOT GLOB '*[^0-9]*' AND ("size_base" = '0' OR "size_base" NOT GLOB '0*') AND (length("size_base") < 20 OR (length("size_base") = 20 AND "size_base" <= '18446744073709551615'))),
  "entry_price_sol_per_token" TEXT NOT NULL CHECK (length("entry_price_sol_per_token") <= 100 AND (CASE WHEN "entry_price_sol_per_token" GLOB '-*' THEN substr("entry_price_sol_per_token", 2) ELSE "entry_price_sol_per_token" END) GLOB '[0-9]*' AND (CASE WHEN "entry_price_sol_per_token" GLOB '-*' THEN substr("entry_price_sol_per_token", 2) ELSE "entry_price_sol_per_token" END) NOT GLOB '*[^0-9.]*' AND (CASE WHEN "entry_price_sol_per_token" GLOB '-*' THEN substr("entry_price_sol_per_token", 2) ELSE "entry_price_sol_per_token" END) NOT GLOB '*.*.*' AND (CASE WHEN "entry_price_sol_per_token" GLOB '-*' THEN substr("entry_price_sol_per_token", 2) ELSE "entry_price_sol_per_token" END) NOT GLOB '*.' AND (CASE WHEN "entry_price_sol_per_token" GLOB '-*' THEN substr("entry_price_sol_per_token", 2) ELSE "entry_price_sol_per_token" END) NOT GLOB '0[0-9]*' AND (instr((CASE WHEN "entry_price_sol_per_token" GLOB '-*' THEN substr("entry_price_sol_per_token", 2) ELSE "entry_price_sol_per_token" END), '.') = 0 OR length((CASE WHEN "entry_price_sol_per_token" GLOB '-*' THEN substr("entry_price_sol_per_token", 2) ELSE "entry_price_sol_per_token" END)) - instr((CASE WHEN "entry_price_sol_per_token" GLOB '-*' THEN substr("entry_price_sol_per_token", 2) ELSE "entry_price_sol_per_token" END), '.') <= 30)),
  "exit_price_sol_per_token" TEXT NOT NULL CHECK (length("exit_price_sol_per_token") <= 100 AND (CASE WHEN "exit_price_sol_per_token" GLOB '-*' THEN substr("exit_price_sol_per_token", 2) ELSE "exit_price_sol_per_token" END) GLOB '[0-9]*' AND (CASE WHEN "exit_price_sol_per_token" GLOB '-*' THEN substr("exit_price_sol_per_token", 2) ELSE "exit_price_sol_per_token" END) NOT GLOB '*[^0-9.]*' AND (CASE WHEN "exit_price_sol_per_token" GLOB '-*' THEN substr("exit_price_sol_per_token", 2) ELSE "exit_price_sol_per_token" END) NOT GLOB '*.*.*' AND (CASE WHEN "exit_price_sol_per_token" GLOB '-*' THEN substr("exit_price_sol_per_token", 2) ELSE "exit_price_sol_per_token" END) NOT GLOB '*.' AND (CASE WHEN "exit_price_sol_per_token" GLOB '-*' THEN substr("exit_price_sol_per_token", 2) ELSE "exit_price_sol_per_token" END) NOT GLOB '0[0-9]*' AND (instr((CASE WHEN "exit_price_sol_per_token" GLOB '-*' THEN substr("exit_price_sol_per_token", 2) ELSE "exit_price_sol_per_token" END), '.') = 0 OR length((CASE WHEN "exit_price_sol_per_token" GLOB '-*' THEN substr("exit_price_sol_per_token", 2) ELSE "exit_price_sol_per_token" END)) - instr((CASE WHEN "exit_price_sol_per_token" GLOB '-*' THEN substr("exit_price_sol_per_token", 2) ELSE "exit_price_sol_per_token" END), '.') <= 30)),
  "gross_pnl_lamports" INTEGER NOT NULL,
  "cost_network_base_lamports" INTEGER NOT NULL CHECK ("cost_network_base_lamports" >= 0),
  "cost_priority_lamports" INTEGER NOT NULL CHECK ("cost_priority_lamports" >= 0),
  "cost_tips_lamports" INTEGER NOT NULL CHECK ("cost_tips_lamports" >= 0),
  "cost_venue_fees_lamports" INTEGER NOT NULL CHECK ("cost_venue_fees_lamports" >= 0),
  "cost_failed_tx_lamports" INTEGER NOT NULL CHECK ("cost_failed_tx_lamports" >= 0),
  "total_costs_lamports" INTEGER NOT NULL CHECK ("total_costs_lamports" >= 0),
  "implicit_slippage_lamports" INTEGER,
  "net_pnl_lamports" INTEGER NOT NULL,
  "net_pnl_bps" INTEGER NOT NULL,
  "net_pnl_usd_e6" INTEGER,
  "exit_reason" TEXT NOT NULL CHECK ("exit_reason" IN ('stop', 'target', 'trailing_stop', 'time_stop', 'manual_close', 'flatten_all', 'risk_breach', 'halt_flatten', 'liquidity_collapse', 'authority_change', 'venue_disabled', 'sentinel_flatten', 'orphan_close', 'written_off', 'other')),
  "source" TEXT NOT NULL CHECK ("source" IN ('live', 'paper', 'sentinel', 'recovered', 'backtest', 'replay')),
  "label" TEXT NOT NULL CHECK ("label" IN ('normal', 'shadow')),
  "entry_signatures" TEXT NOT NULL CHECK (json_valid("entry_signatures")),
  "exit_signatures" TEXT NOT NULL CHECK (json_valid("exit_signatures")),
  "sol_usd_at_close_e6" INTEGER,
  "price_source" TEXT,
  "wallet_pubkey" TEXT CHECK ("wallet_pubkey" IS NULL OR (length("wallet_pubkey") BETWEEN 32 AND 44 AND "wallet_pubkey" NOT GLOB '*[^1-9A-HJ-NP-Za-km-z]*')),
  "supersedes_trade_id" TEXT CHECK ("supersedes_trade_id" IS NULL OR (length("supersedes_trade_id") = 26 AND "supersedes_trade_id" NOT GLOB '*[^0-9A-HJKMNP-TV-Z]*')),
  "created_at" INTEGER NOT NULL CHECK ("created_at" >= 1000000000000 AND "created_at" < 100000000000000),
  PRIMARY KEY ("trade_id"),
  CHECK ("net_pnl_lamports" = "gross_pnl_lamports" - "total_costs_lamports"),
  CHECK ("total_costs_lamports" = "cost_network_base_lamports" + "cost_priority_lamports" + "cost_tips_lamports" + "cost_venue_fees_lamports" + "cost_failed_tx_lamports")
) STRICT`,
  `CREATE INDEX "trade_closed_at" ON "trade" ("closed_at")`,
  `CREATE INDEX "trade_position" ON "trade" ("position_id")`,
  `CREATE TRIGGER "trade_no_update" BEFORE UPDATE ON "trade" BEGIN SELECT RAISE(ABORT, 'append_only'); END`,
  `CREATE TRIGGER "trade_no_delete" BEFORE DELETE ON "trade" WHEN OLD."created_at" > coalesce((SELECT "now_ms" FROM "retention_clock" WHERE "id" = 1), 0) - 220924800 * 1000 OR OLD."created_at" > (unixepoch('now') - 220924800) * 1000 BEGIN SELECT RAISE(ABORT, 'append_only'); END`,
  `CREATE TABLE "cash_flow" (
  "flow_id" TEXT NOT NULL CHECK (length("flow_id") = 26 AND "flow_id" NOT GLOB '*[^0-9A-HJKMNP-TV-Z]*'),
  "kind" TEXT NOT NULL CHECK ("kind" IN ('sweep', 'refill', 'sim_funding', 'external_in', 'external_out')),
  "lamports" INTEGER NOT NULL CHECK ("lamports" >= 0),
  "from_pubkey" TEXT CHECK ("from_pubkey" IS NULL OR (length("from_pubkey") BETWEEN 32 AND 44 AND "from_pubkey" NOT GLOB '*[^1-9A-HJ-NP-Za-km-z]*')),
  "to_pubkey" TEXT CHECK ("to_pubkey" IS NULL OR (length("to_pubkey") BETWEEN 32 AND 44 AND "to_pubkey" NOT GLOB '*[^1-9A-HJ-NP-Za-km-z]*')),
  "signature" TEXT CHECK ("signature" IS NULL OR (length("signature") BETWEEN 64 AND 88 AND "signature" NOT GLOB '*[^1-9A-HJ-NP-Za-km-z]*')),
  "slot" INTEGER,
  "at" INTEGER NOT NULL CHECK ("at" >= 1000000000000 AND "at" < 100000000000000),
  "source" TEXT NOT NULL CHECK ("source" IN ('signer_log', 'chain_scan', 'operator')),
  "created_at" INTEGER NOT NULL CHECK ("created_at" >= 1000000000000 AND "created_at" < 100000000000000),
  PRIMARY KEY ("flow_id")
) STRICT`,
  `CREATE TRIGGER "cash_flow_no_update" BEFORE UPDATE ON "cash_flow" BEGIN SELECT RAISE(ABORT, 'append_only'); END`,
  `CREATE TRIGGER "cash_flow_no_delete" BEFORE DELETE ON "cash_flow" WHEN OLD."created_at" > coalesce((SELECT "now_ms" FROM "retention_clock" WHERE "id" = 1), 0) - 220924800 * 1000 OR OLD."created_at" > (unixepoch('now') - 220924800) * 1000 BEGIN SELECT RAISE(ABORT, 'append_only'); END`,
  `CREATE TABLE "sandwich_check" (
  "fill_id" TEXT NOT NULL CHECK (length("fill_id") = 26 AND "fill_id" NOT GLOB '*[^0-9A-HJKMNP-TV-Z]*'),
  "slot" INTEGER NOT NULL,
  "sandwiched" INTEGER NOT NULL CHECK ("sandwiched" IN (0, 1)),
  "same_pool_before" INTEGER NOT NULL,
  "same_pool_after" INTEGER NOT NULL,
  "reason" TEXT,
  "created_at" INTEGER NOT NULL CHECK ("created_at" >= 1000000000000 AND "created_at" < 100000000000000),
  PRIMARY KEY ("fill_id")
) STRICT`,
  `CREATE TRIGGER "sandwich_check_no_update" BEFORE UPDATE ON "sandwich_check" BEGIN SELECT RAISE(ABORT, 'append_only'); END`,
  `CREATE TRIGGER "sandwich_check_no_delete" BEFORE DELETE ON "sandwich_check" WHEN OLD."created_at" > coalesce((SELECT "now_ms" FROM "retention_clock" WHERE "id" = 1), 0) - 31622400 * 1000 OR OLD."created_at" > (unixepoch('now') - 31622400) * 1000 BEGIN SELECT RAISE(ABORT, 'append_only'); END`,
  `CREATE TABLE "cost_item" (
  "cost_id" TEXT NOT NULL CHECK (length("cost_id") = 26 AND "cost_id" NOT GLOB '*[^0-9A-HJKMNP-TV-Z]*'),
  "attempt_id" TEXT NOT NULL CHECK (length("attempt_id") = 26 AND "attempt_id" NOT GLOB '*[^0-9A-HJKMNP-TV-Z]*'),
  "kind" TEXT NOT NULL,
  "lamports" INTEGER NOT NULL CHECK ("lamports" >= 0),
  "source" TEXT NOT NULL,
  "created_at" INTEGER NOT NULL CHECK ("created_at" >= 1000000000000 AND "created_at" < 100000000000000),
  PRIMARY KEY ("cost_id"),
  UNIQUE ("attempt_id", "kind")
) STRICT`,
  `CREATE TRIGGER "cost_item_no_update" BEFORE UPDATE ON "cost_item" BEGIN SELECT RAISE(ABORT, 'append_only'); END`,
  `CREATE TRIGGER "cost_item_no_delete" BEFORE DELETE ON "cost_item" WHEN OLD."created_at" > coalesce((SELECT "now_ms" FROM "retention_clock" WHERE "id" = 1), 0) - 220924800 * 1000 OR OLD."created_at" > (unixepoch('now') - 220924800) * 1000 BEGIN SELECT RAISE(ABORT, 'append_only'); END`,
  `CREATE TABLE "fixed_cost_item" (
  "item_id" TEXT NOT NULL CHECK (length("item_id") = 26 AND "item_id" NOT GLOB '*[^0-9A-HJKMNP-TV-Z]*'),
  "label" TEXT NOT NULL,
  "monthly_usd_e6" INTEGER NOT NULL,
  "source" TEXT NOT NULL CHECK ("source" IN ('manual', 'invoice')),
  "active_from" INTEGER NOT NULL CHECK ("active_from" >= 1000000000000 AND "active_from" < 100000000000000),
  "active_to" INTEGER CHECK ("active_to" IS NULL OR ("active_to" >= 1000000000000 AND "active_to" < 100000000000000)),
  "created_at" INTEGER NOT NULL CHECK ("created_at" >= 1000000000000 AND "created_at" < 100000000000000),
  "updated_at" INTEGER NOT NULL CHECK ("updated_at" >= 1000000000000 AND "updated_at" < 100000000000000),
  PRIMARY KEY ("item_id")
) STRICT`,
  `CREATE TABLE "price_reference" (
  "asset" TEXT NOT NULL,
  "at" INTEGER NOT NULL CHECK ("at" >= 1000000000000 AND "at" < 100000000000000),
  "usd_e6" INTEGER NOT NULL,
  "source" TEXT NOT NULL,
  "created_at" INTEGER NOT NULL CHECK ("created_at" >= 1000000000000 AND "created_at" < 100000000000000),
  PRIMARY KEY ("asset", "at")
) STRICT`,
  `CREATE TRIGGER "price_reference_no_update" BEFORE UPDATE ON "price_reference" BEGIN SELECT RAISE(ABORT, 'append_only'); END`,
  `CREATE TRIGGER "price_reference_no_delete" BEFORE DELETE ON "price_reference" WHEN OLD."created_at" > coalesce((SELECT "now_ms" FROM "retention_clock" WHERE "id" = 1), 0) - 220924800 * 1000 OR OLD."created_at" > (unixepoch('now') - 220924800) * 1000 BEGIN SELECT RAISE(ABORT, 'append_only'); END`,
  `CREATE TABLE "reservation" (
  "reservation_id" TEXT NOT NULL CHECK (length("reservation_id") = 26 AND "reservation_id" NOT GLOB '*[^0-9A-HJKMNP-TV-Z]*'),
  "intent_id" TEXT NOT NULL CHECK (length("intent_id") = 26 AND "intent_id" NOT GLOB '*[^0-9A-HJKMNP-TV-Z]*'),
  "lamports" INTEGER NOT NULL CHECK ("lamports" >= 0),
  "released_at" INTEGER CHECK ("released_at" IS NULL OR ("released_at" >= 1000000000000 AND "released_at" < 100000000000000)),
  "actual_lamports" INTEGER CHECK ("actual_lamports" IS NULL OR ("actual_lamports" >= 0)),
  "created_at" INTEGER NOT NULL CHECK ("created_at" >= 1000000000000 AND "created_at" < 100000000000000),
  PRIMARY KEY ("reservation_id"),
  UNIQUE ("intent_id")
) STRICT`,
  `CREATE TABLE "token_account" (
  "owner" TEXT NOT NULL CHECK (length("owner") BETWEEN 32 AND 44 AND "owner" NOT GLOB '*[^1-9A-HJ-NP-Za-km-z]*'),
  "mint" TEXT NOT NULL CHECK (length("mint") BETWEEN 32 AND 44 AND "mint" NOT GLOB '*[^1-9A-HJ-NP-Za-km-z]*'),
  "token_program" TEXT NOT NULL CHECK (length("token_program") BETWEEN 32 AND 44 AND "token_program" NOT GLOB '*[^1-9A-HJ-NP-Za-km-z]*'),
  "ata" TEXT NOT NULL CHECK (length("ata") BETWEEN 32 AND 44 AND "ata" NOT GLOB '*[^1-9A-HJ-NP-Za-km-z]*'),
  "exists" INTEGER NOT NULL CHECK ("exists" IN (0, 1)),
  "rent_lamports" INTEGER NOT NULL CHECK ("rent_lamports" >= 0),
  "closed_at" INTEGER CHECK ("closed_at" IS NULL OR ("closed_at" >= 1000000000000 AND "closed_at" < 100000000000000)),
  "janitor_attempts" INTEGER NOT NULL,
  "created_at" INTEGER NOT NULL CHECK ("created_at" >= 1000000000000 AND "created_at" < 100000000000000),
  "updated_at" INTEGER NOT NULL CHECK ("updated_at" >= 1000000000000 AND "updated_at" < 100000000000000),
  PRIMARY KEY ("owner", "mint", "token_program")
) STRICT`,
  `CREATE TABLE "wallet_snapshot" (
  "wallet" TEXT NOT NULL CHECK (length("wallet") BETWEEN 32 AND 44 AND "wallet" NOT GLOB '*[^1-9A-HJ-NP-Za-km-z]*'),
  "at" INTEGER NOT NULL CHECK ("at" >= 1000000000000 AND "at" < 100000000000000),
  "granularity" TEXT NOT NULL CHECK ("granularity" IN ('daily', '30s')),
  "sol_lamports" INTEGER NOT NULL CHECK ("sol_lamports" >= 0),
  "tokens_json" TEXT NOT NULL CHECK (json_valid("tokens_json")),
  "slot" INTEGER NOT NULL,
  "created_at" INTEGER NOT NULL CHECK ("created_at" >= 1000000000000 AND "created_at" < 100000000000000),
  PRIMARY KEY ("wallet", "at")
) STRICT`,
  `CREATE TRIGGER "wallet_snapshot_no_update" BEFORE UPDATE ON "wallet_snapshot" BEGIN SELECT RAISE(ABORT, 'append_only'); END`,
  `CREATE TRIGGER "wallet_snapshot_no_delete" BEFORE DELETE ON "wallet_snapshot" WHEN OLD."created_at" > coalesce((SELECT "now_ms" FROM "retention_clock" WHERE "id" = 1), 0) - (CASE OLD."granularity" WHEN 'daily' THEN 220924800 WHEN '30s' THEN 2592000 END) * 1000 OR OLD."created_at" > (unixepoch('now') - (CASE OLD."granularity" WHEN 'daily' THEN 220924800 WHEN '30s' THEN 2592000 END)) * 1000 BEGIN SELECT RAISE(ABORT, 'append_only'); END`,
  `CREATE TABLE "reconcile_run" (
  "run_at" INTEGER NOT NULL CHECK ("run_at" >= 1000000000000 AND "run_at" < 100000000000000),
  "sol_diff_lamports" INTEGER NOT NULL,
  "token_diffs_json" TEXT NOT NULL CHECK (json_valid("token_diffs_json")),
  "orphans_json" TEXT NOT NULL CHECK (json_valid("orphans_json")),
  "created_at" INTEGER NOT NULL CHECK ("created_at" >= 1000000000000 AND "created_at" < 100000000000000),
  PRIMARY KEY ("run_at")
) STRICT`,
  `CREATE TRIGGER "reconcile_run_no_update" BEFORE UPDATE ON "reconcile_run" BEGIN SELECT RAISE(ABORT, 'append_only'); END`,
  `CREATE TRIGGER "reconcile_run_no_delete" BEFORE DELETE ON "reconcile_run" WHEN OLD."created_at" > coalesce((SELECT "now_ms" FROM "retention_clock" WHERE "id" = 1), 0) - 31622400 * 1000 OR OLD."created_at" > (unixepoch('now') - 31622400) * 1000 BEGIN SELECT RAISE(ABORT, 'append_only'); END`,
  `CREATE TABLE "limit_def" (
  "limit_id" TEXT NOT NULL,
  "short_code" TEXT NOT NULL,
  "label" TEXT NOT NULL,
  "scope" TEXT NOT NULL CHECK ("scope" IN ('global', 'strategy', 'token', 'position')),
  "scope_id" TEXT,
  "kind" TEXT NOT NULL,
  "unit" TEXT NOT NULL CHECK ("unit" IN ('lamports', 'bps', 'count', 'ms')),
  "display_unit" TEXT NOT NULL CHECK ("display_unit" IN ('sol', 'bps', 'pct', 'count', 'minutes')),
  "value" INTEGER NOT NULL,
  "ceiling" INTEGER,
  "action_on_breach" TEXT NOT NULL CHECK ("action_on_breach" IN ('block_entries', 'pause_entries', 'reduce_size', 'halt', 'flatten', 'demote', 'alert_only')),
  "editable" INTEGER NOT NULL CHECK ("editable" IN (0, 1)),
  "created_at" INTEGER NOT NULL CHECK ("created_at" >= 1000000000000 AND "created_at" < 100000000000000),
  "updated_at" INTEGER NOT NULL CHECK ("updated_at" >= 1000000000000 AND "updated_at" < 100000000000000),
  PRIMARY KEY ("limit_id"),
  UNIQUE ("short_code")
) STRICT`,
  `CREATE TABLE "limit_state" (
  "limit_id" TEXT NOT NULL,
  "state" TEXT NOT NULL CHECK ("state" IN ('normal', 'elevated', 'near', 'breached', 'disabled')),
  "usage" INTEGER,
  "last_breach_at" INTEGER CHECK ("last_breach_at" IS NULL OR ("last_breach_at" >= 1000000000000 AND "last_breach_at" < 100000000000000)),
  "created_at" INTEGER NOT NULL CHECK ("created_at" >= 1000000000000 AND "created_at" < 100000000000000),
  "updated_at" INTEGER NOT NULL CHECK ("updated_at" >= 1000000000000 AND "updated_at" < 100000000000000),
  PRIMARY KEY ("limit_id")
) STRICT`,
  `CREATE TABLE "breaker_event" (
  "event_id" TEXT NOT NULL CHECK (length("event_id") = 26 AND "event_id" NOT GLOB '*[^0-9A-HJKMNP-TV-Z]*'),
  "breaker_id" TEXT NOT NULL,
  "tripped" INTEGER NOT NULL CHECK ("tripped" IN (0, 1)),
  "reason" TEXT,
  "at" INTEGER NOT NULL CHECK ("at" >= 1000000000000 AND "at" < 100000000000000),
  "created_at" INTEGER NOT NULL CHECK ("created_at" >= 1000000000000 AND "created_at" < 100000000000000),
  PRIMARY KEY ("event_id")
) STRICT`,
  `CREATE TRIGGER "breaker_event_no_update" BEFORE UPDATE ON "breaker_event" BEGIN SELECT RAISE(ABORT, 'append_only'); END`,
  `CREATE TRIGGER "breaker_event_no_delete" BEFORE DELETE ON "breaker_event" WHEN OLD."created_at" > coalesce((SELECT "now_ms" FROM "retention_clock" WHERE "id" = 1), 0) - 220924800 * 1000 OR OLD."created_at" > (unixepoch('now') - 220924800) * 1000 BEGIN SELECT RAISE(ABORT, 'append_only'); END`,
  `CREATE TABLE "command" (
  "command_id" TEXT NOT NULL CHECK (length("command_id") = 26 AND "command_id" NOT GLOB '*[^0-9A-HJKMNP-TV-Z]*'),
  "type" TEXT NOT NULL CHECK ("type" IN ('halt', 'resume', 'flatten_all', 'close_position', 'set_mode', 'update_limit', 'reset_breaker', 'apply_config', 'ack_alert', 'snooze_alert', 'cancel_scheduled', 'write_off_position', 'close_unsolicited')),
  "params_json" TEXT NOT NULL CHECK (json_valid("params_json")),
  "status" TEXT NOT NULL CHECK ("status" IN ('accepted', 'scheduled', 'executing', 'executed', 'rejected', 'failed', 'cancelled')),
  "action_class" TEXT NOT NULL CHECK ("action_class" IN ('A0', 'A1', 'A2', 'A3')),
  "effective_at" INTEGER CHECK ("effective_at" IS NULL OR ("effective_at" >= 1000000000000 AND "effective_at" < 100000000000000)),
  "actor" TEXT NOT NULL CHECK (json_valid("actor")),
  "state_version_before" INTEGER NOT NULL,
  "state_version_after" INTEGER,
  "reason_code" TEXT,
  "created_at" INTEGER NOT NULL CHECK ("created_at" >= 1000000000000 AND "created_at" < 100000000000000),
  "updated_at" INTEGER NOT NULL CHECK ("updated_at" >= 1000000000000 AND "updated_at" < 100000000000000),
  PRIMARY KEY ("command_id")
) STRICT`,
  `CREATE INDEX "command_status" ON "command" ("status")`,
  `CREATE TABLE "audit_event" (
  "event_id" TEXT NOT NULL CHECK (length("event_id") = 26 AND "event_id" NOT GLOB '*[^0-9A-HJKMNP-TV-Z]*'),
  "seq" INTEGER NOT NULL,
  "at" INTEGER NOT NULL CHECK ("at" >= 1000000000000 AND "at" < 100000000000000),
  "mode" TEXT NOT NULL CHECK ("mode" IN ('backtest', 'replay', 'paper', 'live_small', 'live')),
  "actor_json" TEXT NOT NULL CHECK (json_valid("actor_json")),
  "action" TEXT NOT NULL,
  "action_class" TEXT NOT NULL CHECK ("action_class" IN ('A0', 'A1', 'A2', 'A3')),
  "target" TEXT CHECK ("target" IS NULL OR (json_valid("target"))),
  "before" TEXT CHECK ("before" IS NULL OR (json_valid("before"))),
  "after" TEXT CHECK ("after" IS NULL OR (json_valid("after"))),
  "reason_text" TEXT,
  "command_id" TEXT CHECK ("command_id" IS NULL OR (length("command_id") = 26 AND "command_id" NOT GLOB '*[^0-9A-HJKMNP-TV-Z]*')),
  "result" TEXT NOT NULL CHECK ("result" IN ('accepted', 'scheduled', 'executed', 'rejected', 'failed', 'cancelled')),
  "dialog_version" TEXT,
  "dialog_text_hash" TEXT,
  "session_ref" TEXT NOT NULL,
  "prev_hash" TEXT NOT NULL CHECK (length("prev_hash") = 64 AND "prev_hash" NOT GLOB '*[^0-9a-f]*'),
  "hash" TEXT NOT NULL CHECK (length("hash") = 64 AND "hash" NOT GLOB '*[^0-9a-f]*'),
  "created_at" INTEGER NOT NULL CHECK ("created_at" >= 1000000000000 AND "created_at" < 100000000000000),
  PRIMARY KEY ("event_id"),
  UNIQUE ("hash"),
  UNIQUE ("seq")
) STRICT`,
  `CREATE TRIGGER "audit_event_no_update" BEFORE UPDATE ON "audit_event" BEGIN SELECT RAISE(ABORT, 'append_only'); END`,
  `CREATE TRIGGER "audit_event_no_delete" BEFORE DELETE ON "audit_event" WHEN OLD."created_at" > coalesce((SELECT "now_ms" FROM "retention_clock" WHERE "id" = 1), 0) - 220924800 * 1000 OR OLD."created_at" > (unixepoch('now') - 220924800) * 1000 BEGIN SELECT RAISE(ABORT, 'append_only'); END`,
  `CREATE TABLE "alert" (
  "alert_id" TEXT NOT NULL CHECK (length("alert_id") = 26 AND "alert_id" NOT GLOB '*[^0-9A-HJKMNP-TV-Z]*'),
  "dedupe_key" TEXT NOT NULL,
  "severity" TEXT NOT NULL CHECK ("severity" IN ('info', 'warning', 'critical')),
  "category" TEXT NOT NULL CHECK ("category" IN ('risk', 'execution', 'health', 'cost', 'config', 'security', 'mode', 'reconciliation')),
  "title" TEXT NOT NULL,
  "body" TEXT NOT NULL,
  "state" TEXT NOT NULL CHECK ("state" IN ('open', 'acknowledged', 'snoozed', 'resolved')),
  "occurrences" INTEGER NOT NULL,
  "entity" TEXT CHECK ("entity" IS NULL OR (json_valid("entity"))),
  "acked_by" TEXT,
  "acked_at" INTEGER CHECK ("acked_at" IS NULL OR ("acked_at" >= 1000000000000 AND "acked_at" < 100000000000000)),
  "snoozed_until" INTEGER CHECK ("snoozed_until" IS NULL OR ("snoozed_until" >= 1000000000000 AND "snoozed_until" < 100000000000000)),
  "requires_ack" INTEGER NOT NULL CHECK ("requires_ack" IN (0, 1)),
  "created_at" INTEGER NOT NULL CHECK ("created_at" >= 1000000000000 AND "created_at" < 100000000000000),
  "updated_at" INTEGER NOT NULL CHECK ("updated_at" >= 1000000000000 AND "updated_at" < 100000000000000),
  PRIMARY KEY ("alert_id")
) STRICT`,
  `CREATE UNIQUE INDEX "alert_open_dedupe" ON "alert" ("dedupe_key") WHERE state != 'resolved'`,
  `CREATE TABLE "trial_registry" (
  "trial_id" TEXT NOT NULL CHECK (length("trial_id") = 26 AND "trial_id" NOT GLOB '*[^0-9A-HJKMNP-TV-Z]*'),
  "trial_key" TEXT NOT NULL,
  "kind" TEXT NOT NULL CHECK ("kind" IN ('gate', 'coarse_screen')),
  "strategy_id" TEXT NOT NULL,
  "affects_returns_json" TEXT NOT NULL CHECK (json_valid("affects_returns_json")),
  "dataset_hashes" TEXT NOT NULL CHECK (json_valid("dataset_hashes")),
  "returns_per_day_json" TEXT NOT NULL CHECK (json_valid("returns_per_day_json")),
  "returns_per_trade_json" TEXT NOT NULL CHECK (json_valid("returns_per_trade_json")),
  "metrics_json" TEXT NOT NULL CHECK (json_valid("metrics_json")),
  "run_id" TEXT CHECK ("run_id" IS NULL OR (length("run_id") = 26 AND "run_id" NOT GLOB '*[^0-9A-HJKMNP-TV-Z]*')),
  "created_at" INTEGER NOT NULL CHECK ("created_at" >= 1000000000000 AND "created_at" < 100000000000000),
  PRIMARY KEY ("trial_id"),
  UNIQUE ("trial_key", "kind")
) STRICT`,
  `CREATE TRIGGER "trial_registry_no_update" BEFORE UPDATE ON "trial_registry" BEGIN SELECT RAISE(ABORT, 'append_only'); END`,
  `CREATE TRIGGER "trial_registry_no_delete" BEFORE DELETE ON "trial_registry" BEGIN SELECT RAISE(ABORT, 'append_only'); END`,
  `CREATE TABLE "strategy_stage" (
  "strategy_id" TEXT NOT NULL,
  "stage_entered_at" INTEGER NOT NULL CHECK ("stage_entered_at" >= 1000000000000 AND "stage_entered_at" < 100000000000000),
  "stage" TEXT NOT NULL CHECK ("stage" IN ('research', 'coarse_screened', 'backtest_passed', 'replay_passed', 'paper_passed', 'live_small', 'live', 'failed', 'archived')),
  "strategy_version" INTEGER NOT NULL,
  "trial_key" TEXT NOT NULL,
  "windows_used_json" TEXT NOT NULL CHECK (json_valid("windows_used_json")),
  "entered_by" TEXT NOT NULL,
  "reason" TEXT,
  "created_at" INTEGER NOT NULL CHECK ("created_at" >= 1000000000000 AND "created_at" < 100000000000000),
  PRIMARY KEY ("strategy_id", "stage_entered_at")
) STRICT`,
  `CREATE TRIGGER "strategy_stage_no_update" BEFORE UPDATE ON "strategy_stage" BEGIN SELECT RAISE(ABORT, 'append_only'); END`,
  `CREATE TRIGGER "strategy_stage_no_delete" BEFORE DELETE ON "strategy_stage" BEGIN SELECT RAISE(ABORT, 'append_only'); END`,
  `CREATE TABLE "gate_evaluation" (
  "eval_id" TEXT NOT NULL CHECK (length("eval_id") = 26 AND "eval_id" NOT GLOB '*[^0-9A-HJKMNP-TV-Z]*'),
  "strategy_id" TEXT NOT NULL,
  "stage" TEXT NOT NULL CHECK ("stage" IN ('research', 'coarse_screened', 'backtest_passed', 'replay_passed', 'paper_passed', 'live_small', 'live', 'failed', 'archived')),
  "target_mode" TEXT NOT NULL CHECK ("target_mode" IN ('backtest', 'replay', 'paper', 'live_small', 'live')),
  "trial_key" TEXT NOT NULL,
  "gates_json" TEXT NOT NULL CHECK (json_valid("gates_json")),
  "windows_json" TEXT NOT NULL CHECK (json_valid("windows_json")),
  "all_pass" INTEGER NOT NULL CHECK ("all_pass" IN (0, 1)),
  "at" INTEGER NOT NULL CHECK ("at" >= 1000000000000 AND "at" < 100000000000000),
  "created_at" INTEGER NOT NULL CHECK ("created_at" >= 1000000000000 AND "created_at" < 100000000000000),
  PRIMARY KEY ("eval_id")
) STRICT`,
  `CREATE TRIGGER "gate_evaluation_no_update" BEFORE UPDATE ON "gate_evaluation" BEGIN SELECT RAISE(ABORT, 'append_only'); END`,
  `CREATE TRIGGER "gate_evaluation_no_delete" BEFORE DELETE ON "gate_evaluation" WHEN OLD."created_at" > coalesce((SELECT "now_ms" FROM "retention_clock" WHERE "id" = 1), 0) - 220924800 * 1000 OR OLD."created_at" > (unixepoch('now') - 220924800) * 1000 BEGIN SELECT RAISE(ABORT, 'append_only'); END`,
  `CREATE TABLE "bar_1m" (
  "pool_id" TEXT NOT NULL CHECK (length("pool_id") BETWEEN 32 AND 44 AND "pool_id" NOT GLOB '*[^1-9A-HJ-NP-Za-km-z]*'),
  "minute" INTEGER NOT NULL CHECK ("minute" >= 1000000000000 AND "minute" < 100000000000000),
  "open" TEXT NOT NULL CHECK (length("open") <= 100 AND (CASE WHEN "open" GLOB '-*' THEN substr("open", 2) ELSE "open" END) GLOB '[0-9]*' AND (CASE WHEN "open" GLOB '-*' THEN substr("open", 2) ELSE "open" END) NOT GLOB '*[^0-9.]*' AND (CASE WHEN "open" GLOB '-*' THEN substr("open", 2) ELSE "open" END) NOT GLOB '*.*.*' AND (CASE WHEN "open" GLOB '-*' THEN substr("open", 2) ELSE "open" END) NOT GLOB '*.' AND (CASE WHEN "open" GLOB '-*' THEN substr("open", 2) ELSE "open" END) NOT GLOB '0[0-9]*' AND (instr((CASE WHEN "open" GLOB '-*' THEN substr("open", 2) ELSE "open" END), '.') = 0 OR length((CASE WHEN "open" GLOB '-*' THEN substr("open", 2) ELSE "open" END)) - instr((CASE WHEN "open" GLOB '-*' THEN substr("open", 2) ELSE "open" END), '.') <= 30)),
  "high" TEXT NOT NULL CHECK (length("high") <= 100 AND (CASE WHEN "high" GLOB '-*' THEN substr("high", 2) ELSE "high" END) GLOB '[0-9]*' AND (CASE WHEN "high" GLOB '-*' THEN substr("high", 2) ELSE "high" END) NOT GLOB '*[^0-9.]*' AND (CASE WHEN "high" GLOB '-*' THEN substr("high", 2) ELSE "high" END) NOT GLOB '*.*.*' AND (CASE WHEN "high" GLOB '-*' THEN substr("high", 2) ELSE "high" END) NOT GLOB '*.' AND (CASE WHEN "high" GLOB '-*' THEN substr("high", 2) ELSE "high" END) NOT GLOB '0[0-9]*' AND (instr((CASE WHEN "high" GLOB '-*' THEN substr("high", 2) ELSE "high" END), '.') = 0 OR length((CASE WHEN "high" GLOB '-*' THEN substr("high", 2) ELSE "high" END)) - instr((CASE WHEN "high" GLOB '-*' THEN substr("high", 2) ELSE "high" END), '.') <= 30)),
  "low" TEXT NOT NULL CHECK (length("low") <= 100 AND (CASE WHEN "low" GLOB '-*' THEN substr("low", 2) ELSE "low" END) GLOB '[0-9]*' AND (CASE WHEN "low" GLOB '-*' THEN substr("low", 2) ELSE "low" END) NOT GLOB '*[^0-9.]*' AND (CASE WHEN "low" GLOB '-*' THEN substr("low", 2) ELSE "low" END) NOT GLOB '*.*.*' AND (CASE WHEN "low" GLOB '-*' THEN substr("low", 2) ELSE "low" END) NOT GLOB '*.' AND (CASE WHEN "low" GLOB '-*' THEN substr("low", 2) ELSE "low" END) NOT GLOB '0[0-9]*' AND (instr((CASE WHEN "low" GLOB '-*' THEN substr("low", 2) ELSE "low" END), '.') = 0 OR length((CASE WHEN "low" GLOB '-*' THEN substr("low", 2) ELSE "low" END)) - instr((CASE WHEN "low" GLOB '-*' THEN substr("low", 2) ELSE "low" END), '.') <= 30)),
  "close" TEXT NOT NULL CHECK (length("close") <= 100 AND (CASE WHEN "close" GLOB '-*' THEN substr("close", 2) ELSE "close" END) GLOB '[0-9]*' AND (CASE WHEN "close" GLOB '-*' THEN substr("close", 2) ELSE "close" END) NOT GLOB '*[^0-9.]*' AND (CASE WHEN "close" GLOB '-*' THEN substr("close", 2) ELSE "close" END) NOT GLOB '*.*.*' AND (CASE WHEN "close" GLOB '-*' THEN substr("close", 2) ELSE "close" END) NOT GLOB '*.' AND (CASE WHEN "close" GLOB '-*' THEN substr("close", 2) ELSE "close" END) NOT GLOB '0[0-9]*' AND (instr((CASE WHEN "close" GLOB '-*' THEN substr("close", 2) ELSE "close" END), '.') = 0 OR length((CASE WHEN "close" GLOB '-*' THEN substr("close", 2) ELSE "close" END)) - instr((CASE WHEN "close" GLOB '-*' THEN substr("close", 2) ELSE "close" END), '.') <= 30)),
  "close_depth_lamports" INTEGER NOT NULL CHECK ("close_depth_lamports" >= 0),
  "snapshots" INTEGER NOT NULL,
  "created_at" INTEGER NOT NULL CHECK ("created_at" >= 1000000000000 AND "created_at" < 100000000000000),
  PRIMARY KEY ("pool_id", "minute")
) STRICT`,
  `CREATE TABLE "equity_point" (
  "minute" INTEGER NOT NULL CHECK ("minute" >= 1000000000000 AND "minute" < 100000000000000),
  "mode" TEXT NOT NULL CHECK ("mode" IN ('backtest', 'replay', 'paper', 'live_small', 'live')),
  "equity_lamports" INTEGER NOT NULL CHECK ("equity_lamports" >= 0),
  "flow_adjusted_index" TEXT NOT NULL CHECK (length("flow_adjusted_index") <= 100 AND (CASE WHEN "flow_adjusted_index" GLOB '-*' THEN substr("flow_adjusted_index", 2) ELSE "flow_adjusted_index" END) GLOB '[0-9]*' AND (CASE WHEN "flow_adjusted_index" GLOB '-*' THEN substr("flow_adjusted_index", 2) ELSE "flow_adjusted_index" END) NOT GLOB '*[^0-9.]*' AND (CASE WHEN "flow_adjusted_index" GLOB '-*' THEN substr("flow_adjusted_index", 2) ELSE "flow_adjusted_index" END) NOT GLOB '*.*.*' AND (CASE WHEN "flow_adjusted_index" GLOB '-*' THEN substr("flow_adjusted_index", 2) ELSE "flow_adjusted_index" END) NOT GLOB '*.' AND (CASE WHEN "flow_adjusted_index" GLOB '-*' THEN substr("flow_adjusted_index", 2) ELSE "flow_adjusted_index" END) NOT GLOB '0[0-9]*' AND (instr((CASE WHEN "flow_adjusted_index" GLOB '-*' THEN substr("flow_adjusted_index", 2) ELSE "flow_adjusted_index" END), '.') = 0 OR length((CASE WHEN "flow_adjusted_index" GLOB '-*' THEN substr("flow_adjusted_index", 2) ELSE "flow_adjusted_index" END)) - instr((CASE WHEN "flow_adjusted_index" GLOB '-*' THEN substr("flow_adjusted_index", 2) ELSE "flow_adjusted_index" END), '.') <= 30)),
  "drawdown_bps" INTEGER NOT NULL,
  "created_at" INTEGER NOT NULL CHECK ("created_at" >= 1000000000000 AND "created_at" < 100000000000000),
  PRIMARY KEY ("minute", "mode")
) STRICT`,
  `CREATE TRIGGER "equity_point_no_update" BEFORE UPDATE ON "equity_point" BEGIN SELECT RAISE(ABORT, 'append_only'); END`,
  `CREATE TRIGGER "equity_point_no_delete" BEFORE DELETE ON "equity_point" WHEN OLD."created_at" > coalesce((SELECT "now_ms" FROM "retention_clock" WHERE "id" = 1), 0) - 220924800 * 1000 OR OLD."created_at" > (unixepoch('now') - 220924800) * 1000 BEGIN SELECT RAISE(ABORT, 'append_only'); END`,
  `CREATE TABLE "quarantine" (
  "id" TEXT NOT NULL CHECK (length("id") = 26 AND "id" NOT GLOB '*[^0-9A-HJKMNP-TV-Z]*'),
  "program_id" TEXT NOT NULL CHECK (length("program_id") BETWEEN 32 AND 44 AND "program_id" NOT GLOB '*[^1-9A-HJ-NP-Za-km-z]*'),
  "discriminator" TEXT NOT NULL,
  "raw_b64" TEXT NOT NULL,
  "signature" TEXT CHECK ("signature" IS NULL OR (length("signature") BETWEEN 64 AND 88 AND "signature" NOT GLOB '*[^1-9A-HJ-NP-Za-km-z]*')),
  "first_seen" INTEGER NOT NULL CHECK ("first_seen" >= 1000000000000 AND "first_seen" < 100000000000000),
  "created_at" INTEGER NOT NULL CHECK ("created_at" >= 1000000000000 AND "created_at" < 100000000000000),
  PRIMARY KEY ("id"),
  UNIQUE ("program_id", "discriminator")
) STRICT`,
  `CREATE TRIGGER "quarantine_no_update" BEFORE UPDATE ON "quarantine" BEGIN SELECT RAISE(ABORT, 'append_only'); END`,
  `CREATE TRIGGER "quarantine_no_delete" BEFORE DELETE ON "quarantine" WHEN OLD."created_at" > coalesce((SELECT "now_ms" FROM "retention_clock" WHERE "id" = 1), 0) - 31622400 * 1000 OR OLD."created_at" > (unixepoch('now') - 31622400) * 1000 BEGIN SELECT RAISE(ABORT, 'append_only'); END`,
  `CREATE TABLE "metric_rollup_1m" (
  "metric" TEXT NOT NULL,
  "labels_hash" INTEGER NOT NULL,
  "minute" INTEGER NOT NULL CHECK ("minute" >= 1000000000000 AND "minute" < 100000000000000),
  "scope" TEXT NOT NULL CHECK ("scope" IN ('aggregate', 'pool')),
  "count" INTEGER NOT NULL,
  "sum" REAL NOT NULL,
  "p50" REAL,
  "p95" REAL,
  "p99" REAL,
  "created_at" INTEGER NOT NULL CHECK ("created_at" >= 1000000000000 AND "created_at" < 100000000000000),
  PRIMARY KEY ("metric", "labels_hash", "minute")
) STRICT, WITHOUT ROWID`,
  `CREATE TRIGGER "metric_rollup_1m_no_update" BEFORE UPDATE ON "metric_rollup_1m" BEGIN SELECT RAISE(ABORT, 'append_only'); END`,
  `CREATE TRIGGER "metric_rollup_1m_no_delete" BEFORE DELETE ON "metric_rollup_1m" WHEN OLD."created_at" > coalesce((SELECT "now_ms" FROM "retention_clock" WHERE "id" = 1), 0) - (CASE OLD."scope" WHEN 'aggregate' THEN 31622400 WHEN 'pool' THEN 604800 END) * 1000 OR OLD."created_at" > (unixepoch('now') - (CASE OLD."scope" WHEN 'aggregate' THEN 31622400 WHEN 'pool' THEN 604800 END)) * 1000 BEGIN SELECT RAISE(ABORT, 'append_only'); END`,
  `CREATE TABLE "outbox" (
  "seq" INTEGER PRIMARY KEY AUTOINCREMENT,
  "topic" TEXT NOT NULL CHECK (length(CAST("topic" AS BLOB)) <= 128),
  "payload_json" TEXT NOT NULL CHECK (json_valid("payload_json")),
  "created_at" INTEGER NOT NULL CHECK ("created_at" >= 1000000000000 AND "created_at" < 100000000000000),
  "published_at" INTEGER CHECK ("published_at" IS NULL OR ("published_at" >= 1000000000000 AND "published_at" < 100000000000000))
) STRICT`,
  `CREATE INDEX "outbox_unpublished" ON "outbox" ("seq") WHERE published_at IS NULL`,
  `CREATE INDEX "outbox_published_at" ON "outbox" ("published_at") WHERE published_at IS NOT NULL`,
  `CREATE TABLE "cost_item_correction" (
  "correction_id" TEXT NOT NULL CHECK (length("correction_id") = 26 AND "correction_id" NOT GLOB '*[^0-9A-HJKMNP-TV-Z]*'),
  "cost_id" TEXT NOT NULL CHECK (length("cost_id") = 26 AND "cost_id" NOT GLOB '*[^0-9A-HJKMNP-TV-Z]*'),
  "lamports" INTEGER NOT NULL CHECK ("lamports" >= 0),
  "source" TEXT NOT NULL,
  "at" INTEGER NOT NULL CHECK ("at" >= 1000000000000 AND "at" < 100000000000000),
  "created_at" INTEGER NOT NULL CHECK ("created_at" >= 1000000000000 AND "created_at" < 100000000000000),
  PRIMARY KEY ("correction_id")
) STRICT`,
  `CREATE INDEX "cost_item_correction_cost" ON "cost_item_correction" ("cost_id")`,
  `CREATE TRIGGER "cost_item_correction_no_update" BEFORE UPDATE ON "cost_item_correction" BEGIN SELECT RAISE(ABORT, 'append_only'); END`,
  `CREATE TRIGGER "cost_item_correction_no_delete" BEFORE DELETE ON "cost_item_correction" WHEN OLD."created_at" > coalesce((SELECT "now_ms" FROM "retention_clock" WHERE "id" = 1), 0) - 220924800 * 1000 OR OLD."created_at" > (unixepoch('now') - 220924800) * 1000 BEGIN SELECT RAISE(ABORT, 'append_only'); END`,
  `CREATE TABLE "kv_state" (
  "key" TEXT NOT NULL,
  "value_json" TEXT NOT NULL CHECK (json_valid("value_json")),
  "created_at" INTEGER NOT NULL CHECK ("created_at" >= 1000000000000 AND "created_at" < 100000000000000),
  "updated_at" INTEGER NOT NULL CHECK ("updated_at" >= 1000000000000 AND "updated_at" < 100000000000000),
  PRIMARY KEY ("key")
) STRICT`,
  `CREATE TABLE "retention_clock" (
  "id" INTEGER NOT NULL,
  "now_ms" INTEGER NOT NULL,
  PRIMARY KEY ("id"),
  CHECK ("id" = 1),
  CHECK ("now_ms" >= 0)
) STRICT`,
  `CREATE TABLE "audit_import_cursor" (
  "source" TEXT NOT NULL CHECK ("source" IN ('signer', 'sentinel')),
  "last_seq" INTEGER NOT NULL,
  "created_at" INTEGER NOT NULL CHECK ("created_at" >= 1000000000000 AND "created_at" < 100000000000000),
  "updated_at" INTEGER NOT NULL CHECK ("updated_at" >= 1000000000000 AND "updated_at" < 100000000000000),
  PRIMARY KEY ("source")
) STRICT`,
  `CREATE TABLE "enumerated_pool" (
  "pool_id" TEXT NOT NULL CHECK (length("pool_id") BETWEEN 32 AND 44 AND "pool_id" NOT GLOB '*[^1-9A-HJ-NP-Za-km-z]*'),
  "base_mint" TEXT NOT NULL CHECK (length("base_mint") BETWEEN 32 AND 44 AND "base_mint" NOT GLOB '*[^1-9A-HJ-NP-Za-km-z]*'),
  "is_canonical" INTEGER CHECK ("is_canonical" IS NULL OR ("is_canonical" IN (0, 1))),
  "first_enumerated_at" INTEGER NOT NULL CHECK ("first_enumerated_at" >= 1000000000000 AND "first_enumerated_at" < 100000000000000),
  "last_refresh_at" INTEGER CHECK ("last_refresh_at" IS NULL OR ("last_refresh_at" >= 1000000000000 AND "last_refresh_at" < 100000000000000)),
  "last_quote_real_lamports" INTEGER CHECK ("last_quote_real_lamports" IS NULL OR ("last_quote_real_lamports" >= 0)),
  "last_quote_virtual" TEXT CHECK ("last_quote_virtual" IS NULL OR ("last_quote_virtual" <> '' AND "last_quote_virtual" NOT GLOB '*[^0-9]*' AND ("last_quote_virtual" = '0' OR "last_quote_virtual" NOT GLOB '0*') AND (length("last_quote_virtual") < 20 OR (length("last_quote_virtual") = 20 AND "last_quote_virtual" <= '18446744073709551615')))),
  "last_base_reserve_base" TEXT CHECK ("last_base_reserve_base" IS NULL OR ("last_base_reserve_base" <> '' AND "last_base_reserve_base" NOT GLOB '*[^0-9]*' AND ("last_base_reserve_base" = '0' OR "last_base_reserve_base" NOT GLOB '0*') AND (length("last_base_reserve_base") < 20 OR (length("last_base_reserve_base") = 20 AND "last_base_reserve_base" <= '18446744073709551615')))),
  "last_supply_base" TEXT CHECK ("last_supply_base" IS NULL OR ("last_supply_base" <> '' AND "last_supply_base" NOT GLOB '*[^0-9]*' AND ("last_supply_base" = '0' OR "last_supply_base" NOT GLOB '0*') AND (length("last_supply_base") < 20 OR (length("last_supply_base") = 20 AND "last_supply_base" <= '18446744073709551615')))),
  "last_market_cap_lamports" INTEGER CHECK ("last_market_cap_lamports" IS NULL OR ("last_market_cap_lamports" >= 0)),
  "last_refresh_slot" INTEGER,
  "created_at" INTEGER NOT NULL CHECK ("created_at" >= 1000000000000 AND "created_at" < 100000000000000),
  "updated_at" INTEGER NOT NULL CHECK ("updated_at" >= 1000000000000 AND "updated_at" < 100000000000000),
  PRIMARY KEY ("pool_id")
) STRICT`,
  `CREATE TABLE "discovery_cursor" (
  "source" TEXT NOT NULL,
  "cursor" TEXT NOT NULL,
  "created_at" INTEGER NOT NULL CHECK ("created_at" >= 1000000000000 AND "created_at" < 100000000000000),
  "updated_at" INTEGER NOT NULL CHECK ("updated_at" >= 1000000000000 AND "updated_at" < 100000000000000),
  PRIMARY KEY ("source")
) STRICT`,
  `CREATE TABLE "coverage_report" (
  "day_utc" TEXT NOT NULL,
  "json" TEXT NOT NULL CHECK (json_valid("json")),
  "low_coverage" INTEGER NOT NULL CHECK ("low_coverage" IN (0, 1)),
  "manifest_sha256" TEXT NOT NULL CHECK (length("manifest_sha256") = 64 AND "manifest_sha256" NOT GLOB '*[^0-9a-f]*'),
  "created_at" INTEGER NOT NULL CHECK ("created_at" >= 1000000000000 AND "created_at" < 100000000000000),
  PRIMARY KEY ("day_utc")
) STRICT`,
  `CREATE TRIGGER "coverage_report_no_update" BEFORE UPDATE ON "coverage_report" BEGIN SELECT RAISE(ABORT, 'append_only'); END`,
  `CREATE TRIGGER "coverage_report_no_delete" BEFORE DELETE ON "coverage_report" BEGIN SELECT RAISE(ABORT, 'append_only'); END`,
  `CREATE TABLE "rpc_usage" (
  "provider" TEXT NOT NULL,
  "month" TEXT NOT NULL,
  "units_used" INTEGER NOT NULL,
  "created_at" INTEGER NOT NULL CHECK ("created_at" >= 1000000000000 AND "created_at" < 100000000000000),
  "updated_at" INTEGER NOT NULL CHECK ("updated_at" >= 1000000000000 AND "updated_at" < 100000000000000),
  PRIMARY KEY ("provider", "month")
) STRICT`,
  `CREATE TABLE "universe_manifest" (
  "day_utc" TEXT NOT NULL,
  "sha256" TEXT NOT NULL CHECK (length("sha256") = 64 AND "sha256" NOT GLOB '*[^0-9a-f]*'),
  "path" TEXT NOT NULL,
  "created_at" INTEGER NOT NULL CHECK ("created_at" >= 1000000000000 AND "created_at" < 100000000000000),
  PRIMARY KEY ("day_utc")
) STRICT`,
  `CREATE TRIGGER "universe_manifest_no_update" BEFORE UPDATE ON "universe_manifest" BEGIN SELECT RAISE(ABORT, 'append_only'); END`,
  `CREATE TRIGGER "universe_manifest_no_delete" BEFORE DELETE ON "universe_manifest" BEGIN SELECT RAISE(ABORT, 'append_only'); END`,
  `CREATE TABLE "shadow_result" (
  "shadow_id" TEXT NOT NULL CHECK (length("shadow_id") = 26 AND "shadow_id" NOT GLOB '*[^0-9A-HJKMNP-TV-Z]*'),
  "attempt_id" TEXT NOT NULL CHECK (length("attempt_id") = 26 AND "attempt_id" NOT GLOB '*[^0-9A-HJKMNP-TV-Z]*'),
  "kind" TEXT NOT NULL CHECK ("kind" IN ('buy', 'round_trip')),
  "pool_id" TEXT NOT NULL CHECK (length("pool_id") BETWEEN 32 AND 44 AND "pool_id" NOT GLOB '*[^1-9A-HJ-NP-Za-km-z]*'),
  "notional_lamports" INTEGER NOT NULL CHECK ("notional_lamports" >= 0),
  "model_out" TEXT NOT NULL CHECK ("model_out" <> '' AND "model_out" NOT GLOB '*[^0-9]*' AND ("model_out" = '0' OR "model_out" NOT GLOB '0*') AND (length("model_out") < 20 OR (length("model_out") = 20 AND "model_out" <= '18446744073709551615'))),
  "simulated_out" TEXT CHECK ("simulated_out" IS NULL OR ("simulated_out" <> '' AND "simulated_out" NOT GLOB '*[^0-9]*' AND ("simulated_out" = '0' OR "simulated_out" NOT GLOB '0*') AND (length("simulated_out") < 20 OR (length("simulated_out") = 20 AND "simulated_out" <= '18446744073709551615')))),
  "error_bps" REAL,
  "context_slot" INTEGER,
  "status" TEXT NOT NULL CHECK ("status" IN ('ok', 'sim_error', 'payer_underfunded', 'skipped')),
  "at" INTEGER NOT NULL CHECK ("at" >= 1000000000000 AND "at" < 100000000000000),
  "created_at" INTEGER NOT NULL CHECK ("created_at" >= 1000000000000 AND "created_at" < 100000000000000),
  PRIMARY KEY ("shadow_id")
) STRICT`,
  `CREATE TRIGGER "shadow_result_no_update" BEFORE UPDATE ON "shadow_result" BEGIN SELECT RAISE(ABORT, 'append_only'); END`,
  `CREATE TRIGGER "shadow_result_no_delete" BEFORE DELETE ON "shadow_result" WHEN OLD."created_at" > coalesce((SELECT "now_ms" FROM "retention_clock" WHERE "id" = 1), 0) - 220924800 * 1000 OR OLD."created_at" > (unixepoch('now') - 220924800) * 1000 BEGIN SELECT RAISE(ABORT, 'append_only'); END`,
  `CREATE TABLE "candidate_event" (
  "event_id" TEXT NOT NULL CHECK (length("event_id") = 26 AND "event_id" NOT GLOB '*[^0-9A-HJKMNP-TV-Z]*'),
  "candidate_id" TEXT NOT NULL CHECK (length("candidate_id") = 26 AND "candidate_id" NOT GLOB '*[^0-9A-HJKMNP-TV-Z]*'),
  "pool_id" TEXT NOT NULL CHECK (length("pool_id") BETWEEN 32 AND 44 AND "pool_id" NOT GLOB '*[^1-9A-HJ-NP-Za-km-z]*'),
  "mint" TEXT NOT NULL CHECK (length("mint") BETWEEN 32 AND 44 AND "mint" NOT GLOB '*[^1-9A-HJ-NP-Za-km-z]*'),
  "from_state" TEXT CHECK ("from_state" IS NULL OR ("from_state" IN ('discovered', 'prefiltered_out', 'screening', 'rejected', 'eligible', 'watched', 'signalled', 'in_position', 'cooldown', 'blacklisted', 'stale', 'evicted'))),
  "to_state" TEXT NOT NULL CHECK ("to_state" IN ('discovered', 'prefiltered_out', 'screening', 'rejected', 'eligible', 'watched', 'signalled', 'in_position', 'cooldown', 'blacklisted', 'stale', 'evicted')),
  "reason" TEXT NOT NULL,
  "at" INTEGER NOT NULL CHECK ("at" >= 1000000000000 AND "at" < 100000000000000),
  "created_at" INTEGER NOT NULL CHECK ("created_at" >= 1000000000000 AND "created_at" < 100000000000000),
  PRIMARY KEY ("event_id")
) STRICT`,
  `CREATE INDEX "candidate_event_candidate" ON "candidate_event" ("candidate_id")`,
  `CREATE INDEX "candidate_event_at" ON "candidate_event" ("at")`,
  `CREATE TRIGGER "candidate_event_no_update" BEFORE UPDATE ON "candidate_event" BEGIN SELECT RAISE(ABORT, 'append_only'); END`,
  `CREATE TRIGGER "candidate_event_no_delete" BEFORE DELETE ON "candidate_event" WHEN OLD."created_at" > coalesce((SELECT "now_ms" FROM "retention_clock" WHERE "id" = 1), 0) - 31622400 * 1000 OR OLD."created_at" > (unixepoch('now') - 31622400) * 1000 BEGIN SELECT RAISE(ABORT, 'append_only'); END`,
  `CREATE TABLE "blacklist" (
  "mint" TEXT NOT NULL CHECK (length("mint") BETWEEN 32 AND 44 AND "mint" NOT GLOB '*[^1-9A-HJ-NP-Za-km-z]*'),
  "reason" TEXT NOT NULL,
  "until" INTEGER CHECK ("until" IS NULL OR ("until" >= 1000000000000 AND "until" < 100000000000000)),
  "set_by" TEXT NOT NULL,
  "created_at" INTEGER NOT NULL CHECK ("created_at" >= 1000000000000 AND "created_at" < 100000000000000),
  "updated_at" INTEGER NOT NULL CHECK ("updated_at" >= 1000000000000 AND "updated_at" < 100000000000000),
  PRIMARY KEY ("mint")
) STRICT`,
  `CREATE TABLE "watch_tail" (
  "pool_id" TEXT NOT NULL CHECK (length("pool_id") BETWEEN 32 AND 44 AND "pool_id" NOT GLOB '*[^1-9A-HJ-NP-Za-km-z]*'),
  "until" INTEGER NOT NULL CHECK ("until" >= 1000000000000 AND "until" < 100000000000000),
  "reason" TEXT NOT NULL,
  "evicted_at" INTEGER NOT NULL CHECK ("evicted_at" >= 1000000000000 AND "evicted_at" < 100000000000000),
  "created_at" INTEGER NOT NULL CHECK ("created_at" >= 1000000000000 AND "created_at" < 100000000000000),
  "updated_at" INTEGER NOT NULL CHECK ("updated_at" >= 1000000000000 AND "updated_at" < 100000000000000),
  PRIMARY KEY ("pool_id")
) STRICT`,
  ],
};
